version: '3.8'

services:
    jenkins:
        build:
          context: ./docker
        privileged: true
        environment:
          - CASC_JENKINS_CONFIG=/var/casc_configs
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        container_name: c-jenkins

        volumes:
        - ./casc_configs:/var/casc_configs
